fortran-lang/stdlib

.github/workflows/main.yml

This is an empty CI using GitHub Actions. Once this is in master, we can send PRs modifying it to do what we need.

Add initial GitHub CI

---

.github/workflows/CI.yml

For now only on Linux and only with one compiler.

CI: Test manual Makefiles

---

src/tests/stats/test_mean.f90
src/tests/stats/test_var.f90

Some small issues detected when compiled with ifort 17.0.4

small_corrections: small issues detected when compiled with ifort17.0.4

---

README.md

fixes #154

---

src/stdlib_experimental_stats_var.fypp

Replace "mean" in ERROR message by "var" in `var` functions

Replace mean in ERROR message by var in var functions

---

.gitattributes

Enforce fortran syntax highlighting on fypp files

---

src/stdlib_experimental_stats_cov.fypp
src/tests/stats/test_cov.f90

I added some tests for `cov` and modified 2 functions (when a mask array is provided).

Addition of tests and clarification for cov

---

.github/workflows/doc-deployment.yml
doc/API.md

Set CNAME in github actions

---

.github/workflows/CI.yml

This fixes the MacOS CI issue, updating the gcc version to the right one.

Fixes CI failing on MacOS

---

src/Makefile.manual

Fix missing dependencies in Makefile

---

STYLE_GUIDE.md

Fix wording in style guide for dimension attribute

---

.github/workflows/CI.yml

fixed typo

---

config/CMakeLists.txt

Correctly set CMAKE_INSTALL_MODULEDIR cache variable

---

CHANGELOG.md
doc/specs/index.md
doc/specs/stdlib_random.md
src/CMakeLists.txt
src/Makefile.manual
src/stdlib_random.fypp
src/tests/stats/test_distribution_PRNG.f90

Rename stdlib_stats_distribution_PRNG to stdlib_random

---

.github/workflows/fpm-deployment.yml

Closes #557 
Reported in https://github.com/fortran-lang/setup-fpm/issues/6

Pin specific fpm version

---

.github/PULL_REQUEST_TEMPLATE.md

Create a call for reviewers pull request template

---

README.md

Add hint for building error with make

---

README.md

Fix broken link to fpm in README.md

---

example/strings/example_ends_with.f90
example/strings/example_starts_with.f90

Fix example starts with

---

doc/specs/stdlib_math.md

docs: correct header level in rad2deg
