.github/workflows/main.yml
We will implement macOS and Windows testing in other PRs. This way at
least Linux testing is done.
=> Test every PR and master on Linux

.github/workflows/main.yml
Replaces #30 
Test GFortran 7,8 & 9 on macOS and Linux
Also, install newer CMake on CI using pip.
=> CI(gha): test w/ multiple GFortrans & macOS too

src/CMakeLists.txt, src/stdlib_experimental_ascii.f90, src/tests/CMakeLists.txt, src/tests/ascii/CMakeLists.txt, src/tests/ascii/test_ascii.f90
This PR addresses https://github.com/fortran-lang/stdlib/issues/11 (there are a few open question left there). 
Tested with both the gfortran and Intel Fortran compilers for the 'default' (ascii) character set.
The tests are essentially a port of those at https://github.com/dlang/phobos/blob/master/std/ascii.d (hopefully not a licensing issue?).
=> Add module for validating ASCII characters and upper/lower conversion

src/tests/loadtxt/CMakeLists.txt
Allow the test to run in an out-of-source build tree.
Works by copying the test data to `${CMAKE_CURRENT_BINARY_DIR}`.
=> copy the test datafiles for test_loadtxt

src/tests/ascii/test_ascii.f90
I didn't see this discussed previously--
```fortran
write(*,*)
```
is for printing to console. This makes it harder to recursively search files for where console output is given with special formatting etc. 
I would kindly suggest to consider Fortran 77 standard `print`, which is identical at the [assembly code level](https://www.scivision.dev/print-vs-write-fortran/).
=> Fortran 77 print instead of write(*,*)

.github/workflows/main.yml, .gitignore
Change the github workflow for the cmake build.
I open the PR to trigger the workflow for the branch. The manual makefiles are not touched.
=> set the cmake build to out-of-source

.github/workflows/main.yml, .gitignore, CMakeLists.txt, src/stdlib_experimental_io.f90, src/tests/ascii/CMakeLists.txt, src/tests/loadtxt/CMakeLists.txt, src/tests/loadtxt/test_savetxt.f90
* use CMAKE_Fortran_MODULE_DIRECTORY to avoid introspecting directory structure
* don't build in-source, use test WORKING_DIRECTORY instead
* use modern add_test() syntax to avoid introspecting project directory structure
* use open(..., action=) to help indicate / safeguard intended file use
* don't have to accommodate CMake <= 2.4 circa 2006
closes #47
=> improve cmake build

.github/workflows/main.yml
This adds one in-tree build test for each platform, to ensure our CMake
build system works both out-of-tree as well as in-tree.
In terms of costs, it seems to add 1s on one Linux build, and 3s on one macOS build.
=> Test in-tree builds

.github/workflows/ci_windows.yml
It can be advantageous to have distinct workflows on a per-operating system basis,
to quickly see the scope of a failure.
This CI will fail until the quad-precision code is made conditional on a build system test (CMake >= 3.14 `check_fortran_source_runs()`) to make quad-precision optional in library and tests.
In the library, this can be done via Fortran `submodule`. In the test, it can be done via preprocessor `#ifdef usereal128` or similar introduced via CMake as a result of configure checks
=> ci: add windows workflow

README.md
In this PR, let's try to summarize the agreed upon scope from #1. I suggest we keep this very general, because we will have to discuss in each case the details of what should be in, but it would be very helpful to have general guidelines of what the scope is, to guide people when proposing ideas for `stdlib`.
=> Add initial scope for stdlib

.github/workflows/CI.yml, Makefile.manual, src/Makefile.manual, src/tests/Makefile.manual, src/tests/ascii/Makefile.manual, src/tests/loadtxt/Makefile.manual
* Compile the quadruple precision loadtxt
* Implement "make test" to run tests and run them at the CI
* Create a static libstdlib.a library and use it in tests
* Use more modern syntax and simplify
* Pass in the FC/FCFLAGS variables automatically
* Consolidate stdlib tests targets
=> Refactor the manual Makefiles

src/Makefile.manual, src/tests/Makefile.manual.test.mk, src/tests/ascii/Makefile.manual, src/tests/loadtxt/Makefile.manual
This further reduces the number of lines to maintain in Makefiles. The tests' Makefiles are now very short. In general we now simply list all the source files, similar to CMake.
=> Further Makefile improvements

src/stdlib_experimental_io.f90, src/tests/io/CMakeLists.txt, src/tests/io/Makefile.manual, src/tests/io/test_open.f90, src/tests/io/test_parse_mode.f90
I modified the function `parse_mode` in `stdlib_experimental_io.f90` to be more flexible.
I also added a new test file `test_parse_mode.f90` and removed associated tests from `test_open` (in case we would use a public `parse_mode` only for tests).
I added several cases for testing `parse_mode`.
=> Modification of the function parse_mode in stdlib_experimental_io

src/stdlib_experimental_io.f90, src/stdlib_experimental_optval.f90
using `select case` here is clearer since the condition doesn't need to include spaces, and briefer
also add "pure" where suitable
=> use "select case" for clarity/brevity

CMakeLists.txt, src/f08estop.f90, src/f18estop.f90, src/tests/ascii/test_ascii.f90
also set minimum CMake version to 3.14 per prior discussion and add example check requiring CMake 3.14: real128
=> add missing implicit none, set compiler flags to force implicit none

src/CMakeLists.txt, src/Makefile.manual, src/stdlib_experimental_io.f90, src/stdlib_experimental_kinds.f90, src/stdlib_experimental_optval.f90, src/tests/io/test_loadtxt.f90, src/tests/io/test_loadtxt_qp.f90, src/tests/io/test_savetxt.f90, src/tests/io/test_savetxt_qp.f90
This implements the latest discussion at #25.
=> Add stdlib_experimental_kinds.f90 and use it

src/stdlib_experimental_io.f90, src/tests/io/test_open.f90, src/tests/io/test_parse_mode.f90
Additions/changes:
- some checks in `parse_mode` to return errors for modes such as `rr`, `rw`, `r++t`, `rbt`. (Note: I couldn't add these tests in CMake, or it should be one per file)
- the function `open` can return the `iostat` if requested
- (@certik) since #49 has been closed, `whitechar` is now replaced by `is_blank`
@scivision : Because I added checks in the function `parse_mode`, it uses again `if` statements instead of `select case`. Good for you?
=> Addition of checks and use of stdlib_experimental_ascii

src/stdlib_experimental_io.f90
ifort does not save 2d arrays of "real(kind=qp)" in a rectangular fashion with "*" formatting.
=> Use explicit formatting in qsavetxt

src/stdlib_experimental_io.f90
=> Use access = "stream" by default

.github/workflows/CI.yml, .github/workflows/ci_windows.yml
* broken tests sometimes hang forever, and that's CTest's default, so make CTest have a finite timeout by default
* don't rely on shell-specific `||` to catch test failures, use a platform-agnostic `if:`
* invoke `ctest` directly to allow easier option access
=> ci ctest enhancements

README.md, src/CMakeLists.txt, src/stdlib_experimental_system.F90, src/tests/CMakeLists.txt, src/tests/system/CMakeLists.txt, src/tests/system/test_sleep.f90
There are a number of capabilities it would be useful to bring from
cstdlib and STL. This is an initial demonstration, replacing
the non-cross-compiler sleep() with a standard implementation that
works across compilers and operating systems, with millisecond integer
input.
For example, Intel compilers can hang at runtime if `call sleep()` is used without `use ifport`. This PR technique doesn't suffer from that issue across operating systems and compilers.
There are a number of other useful functions that can be implemented like this, including resolving absolute filenames and expanding ~ to user home path
Adding CI for Windows brought an interesting corner case to light--runtime segfaults on Windows. I don't see these on my Windows Gfortran PC. This is a common type of corner case, …
=> add system module

CMakeLists.txt, src/CMakeLists.txt
This resolves the issue @certik noted in #108 with the NAG compiler not finding the .mod files. It's unclear to me why things worked with other compilers, as this change is not NAG-specific at all.
This also handles installation of the .mod files (or whatever the compiler creates) which was missing before. One question is where the .mod files should be installed. This installs them into `include`, but it is arguably better to install them alongside the library file in the `lib` directory.
I've tested this with Intel and NAG (temporarily using the workarounds from #108).
=> Update CMakeLists handling of .mod files

.github/workflows/CI.yml, ci/install_cmake.sh
=> Do not use pip to install cmake

src/stdlib_experimental_io.f90, src/stdlib_experimental_io.fypp, src/stdlib_experimental_io.md, src/tests/io/test_loadtxt.f90, src/tests/io/test_savetxt.f90
* Addition of a spec (`stdlib_experimental_io.md`) for the procedures in `stdlib_experimental_io.f90` (`loadtxt`, `savetxt`, and `open`). This spec is different than previously because it also describes subroutines.
* Extension of `loadtxt` and `savetxt` to support `integer`.
* The file `stdlib_experimental_io.f90` was generated from the file `stdlib_experimental_io.fypp` using `fypp`.
=> stdlib_experimental_io: addition of a spec and extension of loadtxt and savetxt to support integers

.gitignore, CMakeLists.txt, cmake/stdlib.cmake, src/CMakeLists.txt, src/common.fypp, src/stdlib_experimental_io.fypp, src/stdlib_experimental_stats.fypp, src/stdlib_experimental_stats_mean.fypp
I refactored and reformatted the fypp-templates in order to enhance readability (in CMake as well in source code). I'd suggest to keep fypps impact on code readability as small as possible. See the suggested changes. Feel free to cherry-pick parts, if you don't like the overall style. Commits are in order of relevance.
=> Fypp cleanup

src/stdlib_experimental_stats.fypp, src/stdlib_experimental_stats.md, src/stdlib_experimental_stats_mean.fypp, src/tests/stats/test_mean.f90
* Addition of `mask` in the API of `mean`, as discussed in #128. `NaN` returns are based on `ieee_arithmetic`;
* Update of the spec;
* Correction of a small typo/error introduced in a previous PR (an `integer` array was not converted to `real(dp)` before doing the `sum` (were our tests not severe enough for these scenarions?).
@aradi : I can't request you as reviewer (the system doesn't find you). Could you have also a look, please?
=> mask_mean_dev: addition of a mask in mean API

STYLE_GUIDE.md
This is an omission that was supposed to be part of #60, but we missed
it. This PR fixes it.
=> Fix a typo ("four" instead of "two")

src/tests/stats/test_mean.f90
The original tolerances look arbitrary:
real(sp), parameter :: sptol = 1.2e-06_sp
real(dp), parameter :: dptol = 2.2e-15_dp
but when written using epsilon() they are almost exactly 10x the machine
epsilon for the particular precision kind:
real(sp), parameter :: sptol = 10.06633 * epsilon(1._sp)
real(dp), parameter :: dptol = 9.907919 * epsilon(1._dp)
so I just rounded it to 10:
real(sp), parameter :: sptol = 10 * epsilon(1._sp)
real(dp), parameter :: dptol = 10 * epsilon(1._dp)
which now shows the intent more clearly: the tolerance assumes we lose
one digit of accuracy.
=> Use epsilon() for tolerances

src/common.fypp, src/stdlib_experimental_stats.fypp, src/stdlib_experimental_stats.md, src/stdlib_experimental_stats_mean.fypp, src/tests/stats/test_mean.f90, src/tests/stats/test_mean_f03.f90
Added support and tests for complex types. 
I changed the names of the specific functions, following the convention used in optval.
=> Added support and test for mean of complex arrays

src/stdlib_experimental_optval.md
I based this on the structure of the spec for `mean`. Things I'm not 100% sure of
- Is an "implemented" section necessary for this case?
- Do we want language-defined terms capitalized or formatted some other way, e.g., PRESENT vs present vs `present`?
- Is my mixed usage of "default" and "fallback" a problem?
=> Add spec for optval

src/Makefile.manual, src/tests/Makefile.manual
This PR enables building the new quadrature module, as well as tests, with the manual Makefiles.
=> Enable make for quadrature

src/CMakeLists.txt, src/Makefile.manual, src/stdlib_experimental_stats.fypp, src/stdlib_experimental_stats.md, src/stdlib_experimental_stats_moment.fypp, src/tests/stats/CMakeLists.txt, src/tests/stats/Makefile.manual, src/tests/stats/test_moment.f90
Related to #113
In this __draft pull request__ I propose the implementation of a function for the k-th  order central moment of an array.
[Matlab moment](https://www.mathworks.com/help/stats/moment.html)
[SciPy moment](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.moment.html)
[Julia moment](https://juliastats.org/StatsBase.jl/v0.21/scalarstats.html#StatsBase.moment)
[R moment](https://www.rdocumentation.org/packages/e1071/versions/1.7-3/topics/moment)
[Octave moment](https://octave.sourceforge.io/octave/function/moment.html)
Note: The functions of R and Octave can also return absolute central moment, raw moment, and absolute raw moment.
Returns the _k_-th order central moment of all the elements of `array`, or of the elements of `array` along dimension `dim` if …
=> Addition of a function to compute the k-th order central moment of an array

src/tests/stats/test_mean.f90, src/tests/stats/test_moment.f90, src/tests/stats/test_var.f90, src/tests/stats/test_varn.f90
`ieee_arithmetic` module is added  and `isnan` is replaced to `ieee_is_nan`.
This fixes the issue https://github.com/fortran-lang/stdlib/issues/159.
=> fix build failure with nagfor because of "isnan" (issue #159)

src/stdlib_experimental_io.md, src/stdlib_experimental_optval.md, src/stdlib_experimental_quadrature.md, src/stdlib_experimental_stats.md
Some specs already contain multiple functions. So I thought it could be good to add TOCs for clarity.
Of course, it can be discussed/modified/removed, as usual.
=> Addition of TOCs in Markdown files

.github/workflows/CI.yml
I think I found the issue in #161 for which the Github action failed due to too long times needed for the manual Makefiles.
The issue is that the tests for in-tree builds generate the `.f90` from `fypp` with RANK = 15. Because these are generated before running the manual Makefiles (and that there is no cleaning), the manual Makefiles do not generate them anymore, and try to compile all the `.f90` files generated with RANK=15 (instead of RANK=4 as for CMake).
This proposition fixes this issue (and will fix the issue in #161 once merged there).
Times needed for the checks are also now more manageable.
=> adapt_CI: correction to avoid RANK>4 in Github actions

src/stdlib_experimental_stats.md
Small PR to clarify the examples in the specs for stats (the `reshape` calls made the examples complex IMO).
=> Example in specs for stats

src/stdlib_experimental_error.md
@milancurcic Here is a first draft for the specs about error_stop and check.
=> Spec for error_stop and check

STYLE_GUIDE.md
Lets discuss if this is need or giving to much overhead. For now there is positive (@jvdp1 ) and negative (@certik ) feedback.
In my opinion a standard library should not only provide functionalty, it also should give example how to use a programming language in an elegant way. We decided already in the STYLE_GUIDE.md to include indentation and whitespaces conventions which have of course bigger impact but specifiying that at an end of a scope there should be a closing statment is quite a minor thing so why to draw a line when specifiying the order of attritbutes?
=> specified order of attributes #167

src/CMakeLists.txt, src/stdlib_experimental_stats.fypp, src/stdlib_experimental_stats.md, src/stdlib_experimental_stats_cov.fypp, src/tests/stats/CMakeLists.txt, src/tests/stats/test_cov.f90
Draft proposal for covariance of array elements opened for discussion
Related to #113 
To be discussed:
* Name: the currently proposed name is `cov`. But what about `covariance`,....?
* API: similar to the API of `variance`
* Implementation: only for arrays of rank 1 and rank 2. 
* Implementation: the API accepts only 1 array.
An implementation to compute the covariance among 2 arrays still needs to be done.
Others:
[Octave `cov`](https://octave.sourceforge.io/octave/function/cov.html)
[Matlab `cov`](https://www.mathworks.com/help/matlab/ref/cov.html)
[Julia `cov`](https://docs.julialang.org/en/v1/stdlib/Statistics/#Statistics.cov)
[R `cov`](http://www.r-tutor.com/elementary-statistics/numerical-measures/covariance)
[Numpy `cov`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.c …
=> Covariance of array elements

src/CMakeLists.txt, src/Makefile.manual, src/stdlib_experimental_linalg.fypp, src/stdlib_experimental_linalg.md, src/stdlib_experimental_linalg_diag.fypp, src/tests/CMakeLists.txt, src/tests/linalg/CMakeLists.txt, src/tests/linalg/test_linalg.f90
See proposal in #169 . This is a draft pull request.
This is my first time using the fypp preprocessor, so I decided to only focus on rank-2 arrays to keep things simple and submit a pull request before my focus shifts away from stdlib. Hopefully the API will not need to change if we decide to generalize these to higher rank-matrices, otherwise the generalizations could be placed into a `stdlib_tensor` module in the future.
I am still missing the tests, but thought it would be beneficial to get some feedback on the functions and documentation first.
@jvdp1 Did you use fypp to generate the tests for the statistical routines and then committed only the generated .f90 files?
=> Addition of diag, eye, and trace

src/stdlib_experimental_error.f90, src/stdlib_experimental_io.fypp, src/stdlib_experimental_linalg.fypp, src/stdlib_experimental_stats.fypp
Addition of small descriptions of the different modules for Ford.
Questions: Should we add descritpions for the different functions in the code? Or only in the specs? Or is it possible to combine specs and code through Ford?
@zbeekman @milancurcic @certik
=> Addition of description for Ford

.github/workflows/PR-review.yml, .github/workflows/doc-deployment.yml, API-doc-FORD-file.md, README.md, STYLE_GUIDE.md, WORKFLOW.md, doc/CodeOfConduct.md, doc/License.md, doc/StyleGuide.md, doc/Workflow.md, doc/index.md, doc/specs/index.md, doc/specs/stdlib_experimental_error.md, src/stdlib_experimental_error.f90
The main motivation for this PR is to speed up non-deployment builds which has been accomplished via:
- Only documenting public/protected entities, not private ones
- Reduce `MAXRANK` from 4 to 3
- Turn off graph and search generation on non-deployment builds
In addition, the documentation was fleshed out & improved, primarily in the FORD "pages" section. I used the markdown include capabilities to duplicate/include the LICENSE, WORKFLOW.md, STYLE_GUIDE.md etc. in the "pages" documentation. I also improved the main index.md "pages" landing page and the "specs" landing page.
Furthermore I edited the `stdlib_experimental_error` spec to illustrate the usage of FORD's linking syntax as requested by @jvdp1. It should be noted that we may want to remove the links from the headings as they break …
=> Speed up doc builds & improve documentation

src/stdlib_experimental_linalg_diag.fypp
Mentioned by @MarDiehl in #205 
ifort message:
```
function diag_cdp_mat(A) result(res)
---------------^
/home/jvandenp/stdlib/build/src/stdlib_experimental_linalg_diag.f90(350): error #6645: The name of the module procedure conflicts with a name in the encompassing scoping unit.   [DIAG_CQP_MA
T]
function diag_cqp_mat(A) result(res)
---------------^
/home/jvandenp/stdlib/build/src/stdlib_experimental_linalg_diag.f90(358): error #6645: The name of the module procedure conflicts with a name in the encompassing scoping unit.   [DIAG_IINT8_
MAT]
```
=> Fix for an issue in stdlib_experimental_linalg_diag with Intel compiler

WORKFLOW.md
@milancurcic 
as discussed in #5
=> explicitly state that unit tests are required

src/tests/io/test_savetxt.f90, src/tests/linalg/test_linalg.f90, src/tests/optval/test_optval.f90, src/tests/stats/test_cov.f90, src/tests/stats/test_mean.f90, src/tests/stats/test_var.f90, src/tests/stats/test_varn.f90
"complex" function which is not a fortran standard causes an error like below in nagfor.
(for example)
"Error: test_linalg.f90, line 445: Implicit type for COMPLEX in TEST_TRACE_CQP"
So, "complex" is replaced with "cmplx" which is one of the fortran standard function.
At the same time, I specified the "kind" value so that it has the same precision as the "cmplx" function argument.
=> fix build failure with nagfor7.0 because of using "complex" function

doc/specs/stdlib_experimental_stats.md, src/CMakeLists.txt, src/stdlib_experimental_stats.fypp, src/stdlib_experimental_stats_corr.fypp, src/tests/stats/CMakeLists.txt, src/tests/stats/test_corr.f90
Related to the functions `cov` and `var`
As usual, everything can/must be discussed.
* Octave [corr](https://octave.org/doc/v4.2.1/Correlation-and-Regression-Analysis.html)
* Matlab [corr](https://www.mathworks.com/help/stats/corr.html)
* R [cor](https://www.statmethods.net/stats/correlations.html)
* Julia [cor](https://docs.julialang.org/en/v1/stdlib/Statistics/)
* Numpy [corrcoef](https://docs.scipy.org/doc/numpy/reference/generated/numpy.corrcoef.html)
Returns the Pearson correlation of the elements of `array` along dimension `dim` if the corresponding element in `mask` is `true`.
The Pearson correlation between two rows (or columns), say `x` and `y`, of `array` is defined as:
```
corr(x, y) = cov(x, y) / sqrt( var(x) * var(y))
```
`result = corr(array, dim [, mask])`
`array`: Shall be …
=> Pearson correlation among elements of an array

.github/workflows/doc-deployment.yml
Issue: gfortran was not found for the doc-deployment script.
Installing it solved the problem.
=> Install GFortran macOS in doc-deployment CI

src/stdlib_stats_moment.fypp, src/stdlib_stats_var.fypp, src/tests/stats/test_corr.f90, src/tests/stats/test_mean_f03.f90, src/tests/stats/test_rawmoment.f90, src/tests/stats/test_varn.f90
Addition of some explicit conversions as discussed in the thread starting with [this comment](https://github.com/fortran-lang/stdlib/issues/113#issuecomment-699695493).
=> Explicit conversion

src/stdlib_logger.f90
Currently, a trailing space will be present from the second line (there is no trailing space for the first line (see `format_fist_line` for details).
This PR avoids trailing spaces from the second line.
@wclodius2 What is on purpose that a trailing space remained from the second line?
=> logger: avoid trailing spaces when writing line 2+

src/stdlib_ascii.f90
The comments to the previous pull request are now all solved:
- Extra parentheses have been removed (for readability those around the logical disjunctions and conjunctions have been kept)
- Some clean-up of the comments (more explicitly stating the ranges)
- The functions to_lower and to_upper have been made robust (perhaps slower than before, but the performance is certainly not bad)
Suggestion for further improvement: allow to_lower and to_upper to convert strings of arbitrary length - this seems to me to be the most common usage.
=> Update ascii - second round: clean up the code and implement robust versions of to_lower and to_upper

src/stdlib_logger.f90, src/tests/logger/test_stdlib_logger.f90
A proposition to support `new_line` properly when inserted in a message as, e.g.,:
```fortran
call global % log_message( 'Possible issues: ' // new_line('a') // &
' 1) First possible issue' // new_line('a') // &
' 2) Second possible issue')
=> Logger: support of new_line() in the output of the logger

.github/workflows/doc-deployment.yml
It seems the command `set-env` is deprecated (since it is exploitable), so the Ford CI is failing.
I believe this small fix solves the issue: [GH Workflow environment files](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)
=> Small fix to issue #245

doc/specs/stdlib_logger.md, src/stdlib_logger.f90
@wclodius2 
I found a small issue within `stdlib_logger`. If the subroutine `configuration` is called and no units are associated with the logger, `self % log_units` is not allocated, and leads to a segfault (in debug mode) when the program tries to use it for allocating `log_units`.
With my proposition, `log_units` will be a zero-sized array in such situations (as it is tested like that in the tests).
=> Issue with logger s configuration subroutine

doc/specs/index.md, doc/specs/stdlib_logger.md, src/stdlib_logger.f90, src/tests/logger/test_stdlib_logger.f90
Changes in four files:
* `doc/specs/index.md` - added `stdlib_logger.html` to the index;
* `doc/specs/stdlib_logger.md` - described the changes in `stdlib_logger.f90`;
* `src/tests/logger/test-stdlib_logger.f90` - added a blank after a comma in the output;
* `src/stdlib_logger.f90` - numerous changes
- the code handles `new_line` calls in the message string properly (added by @jvdp1, but undocumented in `stdlib_logger.md`)
- a character string buffer was added to `logger_type` and a`len_buffer` integer to track the number of active characters in the buffer;
- the code replaced multiple calls to write statements with single calls with line breaks generated by inserting `new_line` in the output string, in order to make the output thread and asynchronous IO safe;
- shortened a number of …
=> Logger safe async io

doc/specs/stdlib_bitsets.md, src/stdlib_bitsets.fypp
The following has been done:
* Specs: Correction of some FORD links + typos
* code: addition of links to the specs for easier navigation
=> Update links in stdlib_bitsets to navigate easily from specs to code (and vice versa)

doc/specs/stdlib_logger.md, src/stdlib_logger.f90
I was testing a multi-threading (OpenMP) program with `global_logger` inside an OpenMP loop. I got a `segfault` because a thread tried to allocate `seld % buffer` while it was already allocated by another thread.
As a solution, I moved the variables `self % buffer` and `self % len_buffer` into the subroutines `log_messge` and `log_text_error`. I believe that this solution has been already proposed in another discussion (I can't retrieve it).
Note that this modification solves the problem of `segfault`, but it does not make the logger thread-safe. AFAIK, to be thread-safe, the logger (or the `write` statement inside the logger) should be in an OpenMP critical section.
=> Logger: move self%buffer and seld%len_buffer to local variables

CMakeLists.txt
This PR improves the Fortran 2018 error stop check by running the example and checking for a correctly reported return code from the program.
The current check gives a false positive result for `ifort` 21.1 BETA 20200827, which compiles F18 error stop syntax but does not propagate the error code correctly. Since this is probably a bug I reported this upstream as well:
https://community.intel.com/t5/Intel-Fortran-Compiler/Fortran-2018-error-stop/m-p/1234424#M153065
=> Improve check for F18 error stop

doc/specs/stdlib_logger.md, src/stdlib_logger.f90, src/tests/logger/test_stdlib_logger.f90
Following the discussion in #254, I propose to add a subroutine call `log_debug` with the following API:
Writes the string `message` to `self % log_units` with optional additional text.
`call self % log_debug( message [, module, procedure ] )`
If time stamps are active, a time stamp is written, followed
by `module` and `procedure` if present, and then
`message` is written with the prefix `'DEBUG: '`.
QUESTION: Is this API OK? Or should it be more similar to the API of [`log_error`](https://stdlib.fortran-lang.org/page/specs/stdlib_logger.html#status_5) with `stat` and `errmsg`?
=> debug_logger: add log_debug to logger

.github/workflows/CI.yml
```
rscohn2@rscohn1-MOBL:Debug$ sudo apt-get install intel-oneapi-ifort
[sudo] password for rscohn2:
Reading package lists... Done
Building dependency tree
Reading state information... Done
Note, selecting 'intel-oneapi-compiler-fortran' instead of 'intel-oneapi-ifort'
intel-oneapi-compiler-fortran is already the newest version (2021.1.1-189).
intel-oneapi-compiler-fortran set to manually installed.
0 upgraded, 0 newly installed, 0 to remove and 18 not upgraded.
rscohn2@rscohn1-MOBL:Debug$
```
=> oneapi package name change

src/tests/bitsets/test_stdlib_bitset_64.f90, src/tests/bitsets/test_stdlib_bitset_large.f90
This seems to avoid a filename race conditions on macOS.
Fixes #264.
=> Use distinct file names

.github/workflows/CI.yml, .github/workflows/doc-deployment.yml
To solve issues with Github actions (doc deployment) in #261 and #269.
Apparently `gfortran` (version 10) was renamed `gfortran-10` in MacOS. Therefore, I modified the different scripts to consider it correctly.
I also added `gfortran-10` to the current evaluated versions (7, 8, and 9).
=> Add gfortran 10 to CI

src/CMakeLists.txt, src/Makefile.manual, src/stdlib_stats_moment.fypp, src/stdlib_stats_moment_all.fypp, src/stdlib_stats_moment_mask.fypp, src/stdlib_stats_moment_scalar.fypp
This is an attempt to reduce the memory usage when compiling stdlib with default max rank of 15. Tested with ninja generator (`-G Ninja`) and GCC 10.2 on a laptop with two physical cores and 8GB RAM.
The first commit on this branch allows compilation with *one* ninja job and peak memory usage of ~7GB. The second commit on this branch allows compilation with *two* ninja jobs and peak memory usage of ~7GB.
=> Improve compilation load by splitting stdlib_stats_moment submodule

.github/workflows/ci_windows.yml, src/tests/stats/test_mean.f90
Windows testing is currently limited to the MinGW version preinstalled by choco (GCC 8.1). This PR uses the MSYS2 toolchains to test for the latest GCC/MinGW versions as well.
In total three new CI tests are added:
1. GCC in MSYS POSIX environment
2. native MinGW64 compiler
3. native MinGW32 compiler (see #274 regarding test failure)
With the adjustment of the thresholds in test_mean, this PR also fixes #274
=> Add all three MSYS2 systems to Windows CI

CMakeLists.txt, src/CMakeLists.txt
Required changes to use stdlib as subproject in CMake.
=> Fix subproject build

README.md
- explicitly spell out the requirements on compilers, build system and preprocessor
- add a short paragraph on how to install the build dependencies using pip or conda
- explain the CMake build step by step
- list all important CMake configuration options in the README
- add the CMake install command to the build instructions
- move the paragraph about the max array rank into the build instructions
=> Write a more verbose introduction to building stdlib

CMakeLists.txt, src/CMakeLists.txt, src/tests/CMakeLists.txt, src/tests/system/CMakeLists.txt
Part 2/3 for #287, status: *optional*. If you do not like this approach we can do #287 without it.
*Changes:*
- rename CMake project from `stdlib` to `fortran_stdlib`
- reuse the `PROJECT_NAME` CMake variable instead of using `fortran_stdlib` directly
*Reasoning:*
- exported CMake targets usually match the project name (`fortran_stdlib` seems less likely to clash with something compared to `stdlib`)
- allows to easily use `PROJECT_NAME` to write reusable/transferable CMake code for different projects (interesting for fpm generated CMake files as well)
- `PROJECT_NAME` is accessible in `configure_file` and can be used to create more general template files
=> Rename CMake project from stdlib to fortran_stdlib

CMakeLists.txt, README.md, config/CMakeLists.txt, config/template.cmake, config/template.pc
Part 3/3 for #287, status: *required*.
*Changes:*
- set project version (just 0 as dummy) and project description in CMake (required to generate a valid pc-file)
- export CMake package fortran_lang-config.cmake for CMake projects
- export pkg-config file fortran_lang.pc for non-CMake projects
**Important:** *This PR defines a version number for stdlib. This should be considered carefully (see #292).*
=> Export package files

.github/workflows/CI.yml, src/Makefile.manual
This PR fixes the manual Makefile by including the correct dependencies. The manual Makefile build could fail in full parallel builds due to missing dependencies.
To test this use a slow computer and let make create as many build jobs as allowed by the dependency network with:
```sh
make -f Makefile.manual FYPPFLAGS=-DMAXRANK=4 -j
```
This error might be hard to catch in a sequential CI build due to the correct ordering of the source files in `SRC` variable.
=> Fix dependencies in manual Makefile

src/Makefile.manual
Fixing the following issues related to Makefiles mentioned in #294:
* Generated .f90 files by `fypp` can now be cleaned with the clean rule
* Dependency added for `common.fypp`
=> Fix some issues with Makefiles mentioned in #294

README.md
Add supported compilers MinGW 8, 9, 10 (x86_64 and i686) on Windows 10.
=> Add supported compilers MinGW 8, 9, 10

doc/specs/index.md, doc/specs/stdlib_ascii.md, src/stdlib_ascii.f90, src/tests/ascii/test_ascii.f90
This PR implements some character handling routines discussed in #69, but purposely does not put them into the `stdlib_string` namespace. ~~There is one little caveat with this implementation due to a namespace collision with the `stdlib_ascii` module, which might require reconsidering the naming of the functions implemented here.~~
- extend `to_lower` function to work on character strings
- extend `to_upper` function to work on character strings
- implement `to_title` function
- implement `reverse` function
The change in `stdlib_ascii` might be breaking ABI compatibility with the default branch.
=> Extend stdlib_ascii module for handling character variables

.github/workflows/ci_windows.yml
Fixes recent build failure when installing fypp in the MinGW terminals of the MSYS2 environment.
See: https://github.com/fortran-lang/stdlib/runs/1919864726?check_suite_focus=true
=> Install setuptools for MinGW builds

src/stdlib_quadrature.fypp
Found some occurrences of tabs, which are banned from this code base in the style guide.
=> Style: Remove tabs from code base

README.md, doc/specs/stdlib_string_type.md, src/Makefile.manual, src/stdlib_ascii.f90, src/stdlib_string_type.f90, src/tests/string/test_string_functions.f90
**Status**: open for review.
**Implemented**: the functions asked in #335, added unit tests for each of these functions in `test_string_functions.f90` file and documented the functions in `stdlib_string_type.md` file. (Fixes #335)
**Yet to be done**: https://github.com/fortran-lang/stdlib/pull/346#issuecomment-802004187
**Note**: Please have a look at the recent [suggestion comment ](https://github.com/fortran-lang/stdlib/issues/335#issuecomment-798815164)concerning `to_title` function
I am still trying to get the issues concerning my compiler fixed to run the code on my machine. The code written is **not** checked to run successfully on machine yet. Thus, I kindly request the reviewers to please also run the code once.
=> Added to_lower, to_upper, reverse and to_title function to stdlib_string_type.f90 file

src/tests/string/CMakeLists.txt, src/tests/string/Makefile.manual, src/tests/string/test_string_functions.f90
I was just updating my [`stdlib-fpm`](https://github.com/LKedward/stdlib-fpm) mirror from #346 and I got [a test failure](https://github.com/LKedward/stdlib-fpm/pull/12/checks?check_run_id=2164452169#step:10:1902) in `test_string_functions.f90`; I checked the CI here and noticed the new test wasn't added to the `src/test/CMakeLists.txt` in this repo and so isn't tested in the CI.
- I've added the new test to the CMakeLists file and manual makefile, and;
- Fixed the test by adding a missing 'z' in the compare_string
(A nice demonstration of the benefits of auto-discovery of tests in *fpm*)
=> Add test_string_functions to CMakeLists and fix to_title test

src/tests/Makefile.manual
- use a single target for all, test and clean
- makes it easier to add a new subdirectory without having to modify multiple entries
=> Simplify test makefile

doc/specs/stdlib_ascii.md, doc/specs/stdlib_string_type.md, src/CMakeLists.txt, src/Makefile.manual, src/stdlib_ascii.fypp, src/stdlib_string_type.fypp, src/tests/ascii/test_ascii.f90, src/tests/string/test_string_assignment.f90
- use fypp in `stdlib_ascii` to generate functions for all kind values
=> Add functions to convert integer/logical values to character values

doc/specs/stdlib_strings.md, src/stdlib_strings.f90, src/tests/string/CMakeLists.txt, src/tests/string/Makefile.manual, src/tests/string/test_string_match.f90
This patch implements a simple function to check whether a string starts or ends with a substring, which is a special variant of the intrinsic `index`. A similar `ends_with` function is currently used in the `fpm_strings` module.
```f90
program demo
use stdlib_strings, only : starts_with, ends_with
implicit none
print '(a)', starts_with("pattern", "pat")  ! T
print '(a)', starts_with("pattern", "ern")  ! F
print '(a)', ends_with("pattern", "ern")  ! T
print '(a)', ends_with("pattern", "pat")  ! F
end program demo
```
=> Implement starts_with and ends_with functions

src/tests/bitsets/test_stdlib_bitset_64.f90, src/tests/bitsets/test_stdlib_bitset_large.f90
Changed filenames in test_stdlib_bitsets_64.f90 and test_stdlib_bitsets_large.f90 so that they were no longer the same. Also removed spurious blanks in error stops.
[ticket: X]
=> Changed filenames

.github/ISSUE_TEMPLATE/01_bug.md, .github/ISSUE_TEMPLATE/02_proposal.md
Two issue templates for stdlib:
- bug report
- feature proposal
=> Add issue templates

CONTRIBUTING.md, README.md, doc/contributing/index.md
*This patch will be part of a series of patches to improve the overall developer documentation.*
The current contributing guidelines are quite focused on the workflow and are IMO missing a more general entry point for new contributors. This patch adds an adjusted version of the fpm contributing guidelines as such a more general contributing guideline.
Related issue: #351, https://github.com/fortran-lang/fpm/issues/158, https://github.com/fortran-lang/fpm/pull/160
=> Add general contributing guidelines to stdlib

doc/specs/stdlib_ascii.md, doc/specs/stdlib_string_type.md, src/Makefile.manual, src/stdlib_ascii.fypp, src/stdlib_string_type.fypp, src/tests/ascii/test_ascii.f90, src/tests/string/test_string_functions.f90
Status: Code is open for review
Concerning PR: #372 
Tasks:
Closes https://github.com/fortran-lang/stdlib/pull/372
=> changed to_title to to_sentence and implemented correct to_title

README.md
The Ubuntu version used in CI is 20.04, instead of 18.04 as mentioned in the README.md
=> Corrected Ubuntu version

.github/workflows/CI.yml, CMakeLists.txt, README.md
=> Add GCC-11 to workflow

src/stdlib_logger.f90, src/stdlib_string_type.fypp, src/tests/logger/test_stdlib_logger.f90, src/tests/stats/test_mean_f03.f90
Because of nagfor's strict error checking characteristics, execution is halted by default when a floating point exception occurs. Some of the runtime errors can be resolved by adding the option '-ieee=full'.
Other errors have been corrected to conform more strictly to the fortran standard.
These commit still leaves the one runtime error 'string_derivedtype_io'.
#108
=> Improved support for NAG

doc/specs/stdlib_sorting.md, src/stdlib_sorting.fypp
Some parts of the documentation were missing references to sorting character(len=*) or type(string_type) -- but these are supported.
=> Minor fixes to sorting documentation

doc/specs/index.md, doc/specs/stdlib_kinds.md, src/common.fypp, src/stdlib_ascii.fypp, src/stdlib_kinds.f90, src/stdlib_string_type.fypp, src/tests/ascii/test_ascii.f90, src/tests/string/test_string_assignment.f90
- added logical kind parameters to `stdlib_kinds`:
- `lp`: logical precision of default logical variables (name open for discussion)
- `c_bool`: reexport from `iso_c_binding`
- created `LOG_KINDS`, `LOG_TYPES` and `LOG_KINDS_TYPES` macros
- updated `to_string` generator to use `LOG_KINDS`
- documented `stdlib_kinds` module in specification
Closes #423
=> Add separate logical kind parameters

doc/specs/stdlib_string_type.md, doc/specs/stdlib_strings.md, src/Makefile.manual, src/stdlib_ascii.fypp, src/stdlib_strings.f90, src/tests/string/test_string_functions.f90
Status: code is open for review
resolves #413
Tasks:
=> implemented intelligent slice functionality

src/stdlib_sorting_ord_sort.fypp, src/stdlib_sorting_sort_index.fypp, src/tests/sorting/test_sorting.f90
The option `-fcheck=all` of gfortran triggered a problem with the suboutine `insertion_sort`, when `i` becomes equal to `0`, and tried to access `array( i-1 )` (while the lower bound of `array` is `0`.
The solution copied what was already implemented in `stdlib_sorting_sort.fypp`.
=> Issue with stdlib_sorting

doc/specs/stdlib_strings.md, src/Makefile.manual, src/stdlib_strings.f90, src/tests/string/test_string_functions.f90
=> implemented low level find function for string matching

CMakeLists.txt, README.md
- set default value of 4 to reduce compilation load
=> Make maximum rank an option

doc/specs/stdlib_strings.md, src/stdlib_strings.f90, src/tests/string/test_string_functions.f90
#366 
Current implement provides with `replace_overlapping` optional dummy argument which is `logical`.
This argument helps provide functionality of both OPTION: 1 and OPTION: 2 of [overlapping problem](https://github.com/fortran-lang/stdlib/issues/366#issuecomment-808897041) depending upon whether it is set to `.true.` or `.false.`.
[EDIT]: `replace_overlapping` has been removed from `replace_all` now.
Tasks:
=> implemented low-level replace_all function

doc/specs/index.md
Added missing `stdlb_math` to doc/specs/index.md file.
=> added stdlib_math to specs/index.md

doc/specs/stdlib_strings.md, src/stdlib_strings.f90, src/tests/string/test_string_functions.f90
Counts the number of time substring `pattern` has occurred in the input `string`.
Tasks
=> implemented count function

doc/specs/stdlib_strings.md, src/stdlib_strings.f90, src/tests/string/test_string_functions.f90
=> implemented pad function

doc/specs/stdlib_strings.md
Previously, the documentation was bit lengthy and complex to understand especially for a person learning a programming language for the first time.
Although conceptually documentation is still same but it is simpler and shorter now.
Please let me know which one did you find easier to understand.
=> slice function's documentation made user friendly

.github/workflows/CI.yml, .github/workflows/ci_windows.yml, CMakeLists.txt, README.md
`CMAKE_MAXIMUM_RANK` is now properly defined as a CMake cache variable of type string (even though it functions as an int). Thus, at configure time, it is passed on as `cmake -DCMAKE_MAXIMUM_RANK:String=7`, for instance.
I only changed the semantics of defining the variable -- use `set` instead of `option` -- and updated the README file and CI workflows accordingly.
=> Fix CMake variable usage

src/stdlib_math.fypp, src/stdlib_math_linspace.fypp, src/stdlib_math_logspace.fypp
There is a unreliable behaviour when dealing with negative size at runtime in GCC 11, this bug fix is addressing this issue.
```f90
program main
implicit none
real, allocatable :: x(:)
x = compile_time()
print*, allocated(x) ! T
print*, size(x)      ! 0
x = runtime(100)
print*, allocated(x) ! T
print*, size(x)      ! 100
x = runtime(-100)
print*, allocated(x) ! F -> this is a problem!
print*, size(x)      ! 0
x = runtime(0)
print*, allocated(x) ! T
print*, size(x)      ! 0
x = fix_runtime(-100)
print*, allocated(x) ! T
print*, size(x)      ! 0
contains
function compile_time() result(res)
real :: res(-100)
end function
function runtime(n) result(res)
integer, intent(in) :: n
real :: res(n)
end function
function fix_runtime(n) result(res)
integer, intent(in) :: n
real :: res(merge(n, 0, n > …
```
=> Bug fix: Allocatable argument 'x' is not allocated #472

README.md
Remove GCC Fortran MinGW 8.4.0 from known to work list.
Reference: https://github.com/fortran-lang/stdlib/pull/430
=> Remove GCC Fortran MinGW 8.4.0 from known to work list

CONTRIBUTORS.md, LICENSE
Small housekeeping PR.
* Updates the Copyright statement
* Removes an old and unused Markdown file
```
-Copyright (c) 2019 Fortran stdlib developers
+Copyright (c) 2019-2021 stdlib contributors
```
While I initially wrote "Fortran stdlib developers", I think "contributors" is more clear what it means--everybody who contributed code to stdlib.
Alternatively, this could also be just "Fortran-lang" as a whole, but I wasn't sure.
I request reviews because of this uncertainty, otherwise this is a straightforward PR.
=> Update copyright and remove old artifact

doc/specs/stdlib_error.md, doc/specs/stdlib_string_type.md
Could someone link the file to where the documentation standard is desribed?
I was reading through some documents in `doc/specs` and realised differenced between those documents.
Mostly the layout looks like following:
```markdown
---
title: <MODULE_NAME>
---
[TOC]
```
`stdlib_ascii.md` and a lot of other modules are following this convention, but some do not. Sometimes the order of the subsections describing the procedures are different or some subsections are missing. In other documents the hierarchy level is changed. Do you feel there is a need to address this issues? Should this be continued to be discussed in #181 ?
=> refactor documentation regarding consistency

src/stdlib_sorting.fypp, src/stdlib_sorting_ord_sort.fypp, src/stdlib_sorting_sort.fypp, src/stdlib_sorting_sort_index.fypp
Previously all sorting subroutines for `integer`, `real`, and `string` were generated with `fypp`. `character` had its own subroutines.
I noticed that some checks were not present in `character`-based subroutines, while present for other types. Therefore, I modified the fypp instructions, such that the sorting subrotuines are generated from a same template for `integer`, `real`, `string`, and `character`.
With this strategy, if someone implements a derived type associated with `>`, `<`, `==`,...., the sorting subroutines can be easily implemented for this DT by modifying only the fypp instructions.
Additional reviewer: @wclodius2
=> Generating sorting subroutines specific to `character` type with fypp

Makefile.manual, README.md
These edits to the README attempt to offer simple guidance on compiling stdlib with optimization flags.
In this discussion [here](https://github.com/fortran-lang/stdlib/issues/524) it became clear that not everyone understands how to apply compiler optimizations to stdlib, although the discussion shows that is quite important for performance. 
I think some simple pointers would help users who do not have much experience with build tools (like me!).
=> Make it clearer how the user can control compiler optimization

src/stdlib_bitsets.fypp, src/stdlib_bitsets_64.fypp, src/stdlib_bitsets_large.fypp, src/stdlib_logger.f90, src/stdlib_sorting.fypp, src/stdlib_sorting_ord_sort.fypp, src/stdlib_sorting_sort.fypp, src/stdlib_sorting_sort_index.fypp, src/stdlib_stats_distribution_PRNG.fypp, src/stdlib_stats_moment_all.fypp, src/stdlib_string_type.fypp
With this PR I tried to reduce redundancy, primary by using the `optval` function.
Some discoveries I made while working on this:
- In `stdlib_io` the `open` statement is used with an optional `iostat` argument. Since `open` is an intrinsic function and not a routine, the optional argument cannot be directly passed, which leads to the `open` statement being defined twice. If it doesn't cause too much overhead I suggest to declare an extra variable which will always be passed to the `iostat` argument of the `open` statement. If the optional `iostat` argument of the `open` function is present, the result will then be written to the optional argument.
- The `simps_weights` function (`stdlib_quadrature_simps.fypp`) contains an nested `if` statement which could be rewritten as `select case ( …
=> Reduce redundancy caused by optional arguments

doc/specs/stdlib_math.md, src/stdlib_math.fypp, src/tests/math/test_stdlib_math.f90
Closes #515
1. Add elemental integer function gcd to calculate the greatest common divisor of two numbers
a. Handle negative input as positive
2. Add tests (special, normal, swapped, negative, integer kinds)
=> Add function gcd

src/stdlib_string_type.fypp, src/tests/string/test_string_operator.f90
Found a bug in `string_type` concat where `lhs` and `rhs` were the wrong way around. Added proper tests and fixed it.
=> Fix string concat

CHANGELOG.md, CMakeLists.txt, ci/fpm.toml, doc/changelog.md
Create first release for stdlib. The release notes will be build from the current changelogs entries, feel free to suggests additions to the changelog. After this patch is merged, a new release will be tagged with `v0.1.0`.
*Features, proposals, and fixes that should be included in the first release of the Fortran standard library (0.1.0) should be added to the milestone [v0.1.0](https://github.com/fortran-lang/stdlib/milestone/1).*
Closes #292 
~~Requires #537~~
=> Bump stdlib version to 0.1.0

doc/specs/stdlib_math.md, src/stdlib_math.fypp, src/stdlib_math_linspace.fypp
While working on #504 I noticed that `linspace` and `logspace` in `stdlib_math` aren't declared as `pure`, even though they don't have side effects. This PR makes them `pure`.
=> Make `linspace` and `logspace` pure functions

doc/specs/stdlib_stringlist_type.md
I was reading and testing the module `stdlib_stringlist_type.f90` when I found a few issues related to FORD links. These should fix some of them
=> fix some FORD links

doc/specs/stdlib_string_type.md, src/stdlib_string_type.fypp, src/tests/string/test_string_intrinsic.f90
- interface `string_type` procedure
- `new_string`
- `new_string_from_integer`
- `new_string_from_logical`
- ~~interface `char` procedure~~
- ~~`char_string`~~
- ~~`char_string_range`~~
- ~~private function `maybe`~~
- interface `move` procedure
- `move_string_string`
- interface `move` procedure
- `move_char_string`
- `move_char_string`
- `move_char_char`
Here I have updated the elemental attributes of the routine. There are two areas that are doubtful ❓, but I think they can be `elemental`.
There is another issue. 
`string_type` interface relies on the `to_string` routine, it can convert `character`, `integer`, and `logical` variables into strings and **be elemental** because `type(string_type)` can be non-allocatable, but it does not support the `format` argument. 
While `to_string` …
=> Minor update `pure/elemental` in `string_type` module

CMakeLists.txt
Provide a better error message in case the fypp preprocessor cannot be found by CMake. Point the user to the installation instructions at https://fypp.readthedocs.io/en/stable/fypp.html#installing
=> Update error in case fypp preprocessor is not found

doc/specs/stdlib_stats.md
I added the `intent()` status to all arguments in `stdlib_stats.md` (they are all `intent(in)`).
=> Update of stdlib_stats.md

doc/specs/stdlib_io.md, src/CMakeLists.txt, src/Makefile.manual, src/stdlib_io_npy.fypp, src/stdlib_io_npy_load.fypp, src/stdlib_io_npy_save.fypp, src/tests/io/CMakeLists.txt, src/tests/io/Makefile.manual, src/tests/io/test_npy.f90
Related:
- NumPy documentation https://numpy.org/doc/stable/reference/generated/numpy.lib.format.html
- https://github.com/fortran-lang/stdlib/issues/486
- @MRedies implementation for saving in npy and npz format: https://github.com/MRedies/NPY-for-Fortran
- https://github.com/MRedies/NPY-for-Fortran/issues/5
Hexdumps of `npy` files for reference:
```
00000000  93 4e 55 4d 50 59 02 00  46 00 00 00 7b 27 64 65  |.NUMPY..F...{'de|
00000010  73 63 72 27 3a 20 27 3c  66 38 27 2c 20 27 66 6f  |scr': '<f8', 'fo|
00000020  72 74 72 61 6e 5f 6f 72  64 65 72 27 3a 20 54 72  |rtran_order': Tr|
00000030  75 65 2c 20 27 73 68 61  70 65 27 3a 20 28 31 30  |ue, 'shape': (10|
00000040  2c 34 2c 29 2c 20 7d 20  20 20 20 20 20 20 20 20  |,4,), }         |
00000050  20 0a 00 00 00 00 00 00  00 00 00 00 00 …
```
=> Add routines for saving/loading arrays in npy format

.github/workflows/CI.yml, ci/install_cmake.sh
We are currently pinning CMake to version 3.16 in our CI, which doesn't allow to raise an error in case CTest doesn't find any tests. Unless there is a particular reason to test with CMake 3.16, we can use this PR to use the preinstalled CMake 3.22 version.
Closes #587
=> Error on no tests in CTest

doc/specs/stdlib_selection.md, src/stdlib_selection.fypp
* I corrected some typos in `stdlib_selection.md`
* I added some checks to ensure that `k` in `select(x, k, kth, letft, right)` is within the interval `[left: right]`.
ping @gareth-nx
=> stdlib_selection: correction of typos and addition of some checks

.github/workflows/CI.yml, Makefile.manual, README.md
=> Fix compilation errors with makefiles due to command-line variable assignments

doc/specs/stdlib_stats.md, src/Makefile.manual, src/stdlib_stats_median.fypp, src/tests/stats/test_median.fypp
Based on the performance tests reported in stdlib_selection.md, I replaced all calls to `sort` by `select` in `stdlib_stats_median.fypp`.
=> Replace the call to sort by select in stdlib_stats_median

README.md
This removes the use of the option `-flto` in the instructions to compile with a Makefile.
The reason for doing that is that currently, `-flto` can cause some tests to break - see [discussion here](https://github.com/fortran-lang/stdlib/issues/592#issuecomment-991863294).
Note -- this pull request initially had a failing github test. But that issue must be unrelated to this commit, because the changes here only affect README.md
=> Minor update to makefile installation instructions

API-doc-FORD-file.md, CONTRIBUTING.md, STYLE_GUIDE.md, src/stdlib_selection.fypp
- use HEAD to reference latest commit, which is independent of branch name
=> Rename references to default branch

src/stdlib_io_npy_save.fypp, src/tests/io/test_npy.f90
This is currently just a draft for a minor issue remaining in #581.
I've added a test to check that iomsg is deallocated if present, although this should technically be guaranteed by a standard-conforming compiler when the `intent(out)` attribute is present. 
To make sure the message gets allocated I need a way to trigger `stat /= 0`. Is their any known way of doing this for a new file?
On more thought, I'm afraid that both `stat` and `iomsg` only communicate the result of the command `close()`, and not if opening or writing were unsuccessful. I'm not sure whether the standard stipulates these commands be connected (in other words whether the same I/O error will trigger the same iostat flag in any of the three commands).
=> Fix iomsg allocation in save_npy

CHANGELOG.md, doc/specs/stdlib_io.md, src/Makefile.manual, src/stdlib_io.fypp, src/tests/io/CMakeLists.txt, src/tests/io/Makefile.manual, src/tests/io/test_getline.f90
<details><summary>Alternative implementation by John @urbanjost in M_io</summary>
```f90
!!##NAME
!!    getline(3f) - [M_io] read a line from specified LUN into allocatable string up to line length limit
!!    (LICENSE:PD)
!!
!!##SYNTAX
!!   function getline(line,lun) result(ier)
!!
!!    character(len=:),allocatable,intent(out) :: line
!!    integer,intent(in),optional              :: lun
!!    integer,intent(out)                      :: ier
!!
!!##DESCRIPTION
!!    Read a line of any length up to programming environment maximum
!!    line length. Requires Fortran 2003+.
!!
!!    It is primarily expected to be used when reading input which will
!!    then be parsed.
!!
!!    The input file must have a PAD attribute of YES for the function
!!    to work properly, which is typically true. …
```
=> Add getline to read whole line from formatted unit

CHANGELOG.md, doc/specs/index.md, doc/specs/stdlib_array.md, src/CMakeLists.txt, src/Makefile.manual, src/stdlib_array.f90, src/tests/CMakeLists.txt, src/tests/Makefile.manual, src/tests/array/CMakeLists.txt, src/tests/array/Makefile.manual, src/tests/array/test_logicalloc.f90
=> Implement trueloc/falseloc

doc/specs/index.md, doc/specs/stdlib_ascii.md, doc/specs/stdlib_bitsets.md, doc/specs/stdlib_hash_procedures.md, doc/specs/stdlib_io.md, doc/specs/stdlib_random.md, doc/specs/stdlib_selection.md, doc/specs/stdlib_sorting.md, doc/specs/stdlib_string_type.md, doc/specs/stdlib_stringlist_type.md, doc/specs/stdlib_strings.md, doc/specs/stdlib_version.md
This PR:
* Renames several spec title attributes to make them consistent with others (module names)
* A few similar edits to the index.md of the Spec top-level page, for consistency.
Closes #608.
=> Consistent spec titles

doc/specs/stdlib_hash_procedures.md
The tables in `stdlib_hash_procedures.md` were not correctly setup by `ford`. This PR should fix them.
=> Fixed tables in stdlib_hash_procedures.md

CHANGELOG.md, doc/specs/stdlib_math.md, src/CMakeLists.txt, src/Makefile.manual, src/stdlib_math.fypp, src/stdlib_math_diff.fypp, src/tests/math/test_stdlib_math.fypp
Computes differences between adjacent elements of an array.
**Note**: Only `diff` for `rank-1/rank-2` arrays at this stage. (If there is a higher `rank` demand in the future, we can consider extending it.)
API: 
For a rank-1 array
```fortran
y = [[stdlib_math(module):diff(interface)]](x [, n=1, prepend=<no value>, append=<no value>])
```
and for a rank-2 array
```fortran
y = [[stdlib_math(module):diff(interface)]](x [, n=1, dim=1, prepend=<no value>, append=<no value>])
```
- `X`: `real/integer` types.
- `n`: Difference order.
- ...
Originally `diff` should be putted in `stdlib_linalg`, but considering that `diff` can support `date` drived types in the future, now it is putted in `stdlib_math`.
- [keurfonluu/forlab](https://github.com/keurfonluu/Forlab/blob/master/src/lib/forlab.f90#L2673) …
=> [stdlib_math] Add function `diff`

CMakeLists.txt, README.md, src/CMakeLists.txt
Removed enable_testing(), since this seems to be enabled when the subdirectory "tests" is added.
Used the intrinsic CTests name BUILD_TESTING, ref: https://cmake.org/cmake/help/latest/module/CTest.html.
From my understanding, maybe the ideal way of tackling this issue would be to handle BUILD_TESTING as an intrinsic setting in test-drive? Then we might not need the
`option(BUILD_TESTING "Define if tests should be enabled" ON)`
in CMakeLists.txt
=> option to disable testing by setting BUILD_TESTING to OFF

CMakeLists.txt, config/DefaultFlags.cmake
=> Only set Fortran arguments for Fortran compiler

src/stdlib_io_npy_load.fypp, src/stdlib_io_npy_save.fypp
32-bit integer overflows in `stdlib_io_npy_save.fypp` and `stdlib_io_npy_load.fypp` are fixed from `2**32` to `2**24`, to become the power of base-number (256) at the 4th digit a base-256 number.
To improve readability and understandability, the powers of base-number are refactored from `2**8`, `2**16`, `2**24` to `256**1`, `256**2`, `256**3`, respectively.
The tasks done are summarized as follows:
- fixed and refactored `stdlib_io_npy_save.fypp`
- fixed and refactored `stdlib_io_npy_load.fypp`
- built with gfortran 10.3, ifort 2021.1, and nagfor 7.1 on Windows 10 with cmake 3.20.3
- executed `cmake --build build --target test` to run the test npy and confirmed it passed
closes #647 
Note that `config/DefaultFlags.cmake` is locally changed to specify compiler flags for nagfor as follows: …
=> fixed 32-bit integer overflow in stdlib_io_npy

src/stdlib_quadrature_gauss.f90, src/tests/quadrature/test_gauss.f90
fixes https://github.com/fortran-lang/stdlib/issues/619
=> Fix erroneous gaussian quadrature points in gauss_legendre

doc/specs/stdlib_io.md, src/stdlib_io.fypp, src/tests/io/test_loadtxt.f90
Hey there,
I needed to skip rows with loadtxt, so I added this feature similar to the numpy routine. In addition, I also added `max_rows`.
Added optional arguments:
- `skiprows`: skipping rows at the beginning of the file (default 0)
- `max_rows`: maximum for read lines (default -1 for all lines)
Argument names are taken from `numpy.loadtxt`. All negative values for `max_rows` are interpreted as "all lines".
=> Feature: loadtxt skiprows and max_rows

doc/specs/stdlib_hashmaps.md, doc/specs/stdlib_io.md, src/stdlib_hashmap_wrappers.f90
Some few corrections (typos, wrong declarations, interface issues) (mainly in the specs)
=> Some corrections in the specs

src/stdlib_strings_to_string.fypp, src/tests/string/test_string_to_string.f90
=> Avoid overflow in to_string for -huge(1)-1

.github/workflows/doc-deployment.yml
This PR focuses on fixing `ford`'s version (now it is `ford-6.1.10`) for CI stability and using `ubuntu` to install `ford`.
Close #673.
(PS. Once we know that [ford/issue/446](https://github.com/Fortran-FOSS-Programmers/ford/issues/446) is fixed, we can update the `ford` version later if necessary.)
=> Fixes #673: update docs CI

doc/specs/stdlib_linalg.md, example/linalg/example_cross_product.f90, src/CMakeLists.txt, src/stdlib_linalg.fypp, src/stdlib_linalg_cross_product.fypp, test/linalg/test_linalg.fypp
Cross product of two vectors.
#457
=> cross product of two vectors

.github/workflows/CI.yml, README.md
This PR updates the GCC versions in the OS matrix from [9, 10, 11] to [10, 11, 12]. I did this for both macOS and Ubuntu to keep gcc version parity between 2 OSs, and to not introduce complexity to the CI.yml, the syntax of which I'm still becoming familiar and am not 100% comfortable. Let's hope this works. The brew install step for gcc-11 and gcc-12 on macOS is not necessary because they're provided by the system, but I assume it doesn't hurt and keeps the CI.yml simpler. I hope this works.
Closes #696.
=> Update GCC versions in OS matrix

src/stdlib_hashmap_open.f90
Based on issue #704, I added a presence check for the optional argument `exists` in `get_other_open_data` to fix the access violation due to assignment to an optional variable that was not presented.
The tasks done are summarized as follows:
- Fixed stdlib_hashmap_open.f90.
- Built using gfortran 11.2 bundled with quickstart Fortran on Windows 10 with cmake 3.20.3.
- Executed `cmake --build build --target test` to run the tests and confirmed all tests passed.
- Executed examples below that were using the `open_hashmap_type` and confirmed those finished successfully.
- example_hashmaps_entries.f90
- example_hashmaps_loading.f90
- example_hashmaps_rehash.f90
- example_hashmaps_remove.f90
- example_hashmaps_set_other_data.f90
closes #704
=> Fixed access violation in a type-bound procedure of `open_hashmap_type`

src/stdlib_io_npy_load.fypp
Fixes #709 as proposed by @degawa
I just moved the assignment to the start of the routine so its clear that if nothing changes that `stat` variable, it defaults to zero.
=> Fixes #706 - failure due unassigned value to a intent(out) variable.

src/stdlib_io_npy_load.fypp
Thank you, @14NGiestas and @jvdp1, for fixing issue #706 I reported.
Although you solved the issue (any value is not assigned to an intent(out) argument) found in `get_descriptor`, I discovered that the same problem still exists in `parse_header` called in `get_descriptor`.
I am sending this pull request to fix the issue. I would be happy if you reviewed the pull request.
This pull request fixes the failure of `test_npy`.
```console
stdlib>fpm test test_npy --compiler nagfor --profile release --flag "-fpp"
Project is up to date
Starting read-rdp-r2 ... (1/21)    
... read-rdp-r2 [FAILED]      
Message: Reading of npy file failed
Starting read-rdp-r3 ... (2/21)    
... read-rdp-r3 [FAILED]      
Message: Reading of npy file failed
Starting read-rsp-r1 ... (3/21)    
... read-rsp-r1 …
```
=> fixed unassigned value to a intent(out) variable in `parse_header`

ci/fpm-deployment.sh
Regarding issue #705, I fixed `./ci/fpm-deployment.sh` by adding commands to copy `*.dat` and `*.npy` files.
A diff between the outputs of the scripts before and after the fix shows the `*.dat` and `*.npy` files are copied.
```console
~/stdlib$ git switch master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.
~/stdlib$ bash ./ci/fpm-deployment.sh > current.log
~/stdlib$ rm -rf stdlib-fpm/
~/stdlib$ bash ./ci/fpm-deployment.sh > fixed.log
~/stdlib$ diff current.log fixed.log 
5a6, 7
> example.dat
> example.npy
```
closes #705
=> fixed a problem with `dat` and `npy` files in example dir not being deployed

src/stdlib_random.fypp
``` c
static inline uint64_t rotl(const uint64_t x, int k) {
return (x << k) | (x >> (64 - k));
}
```
fortran has the intrinsic bit function `ishftc(x,k)` ,it is same as rtol
=> change stdlib-random function `rtol` to `ishftc`

src/stdlib_stats_distribution_normal.fypp
This is a very minor fix related to PRE #679. I had forgotten to remove an unused module.
=> Remove unused module `stdlib_error` from module `stdlib_stats_distribution_normal`

doc/specs/stdlib_sorting.md, example/sorting/CMakeLists.txt, example/sorting/example_radix_sort.f90, src/CMakeLists.txt, src/stdlib_sorting.fypp, src/stdlib_sorting_radix_sort.f90, test/sorting/test_sorting.f90
For build-in types, radix_sort is faster in most cases than compare based sort algorithm.
=> Add radix_sort

doc/specs/stdlib_stats_distribution_exponential.md, example/stats_distribution_exponential/example_exponential_cdf.f90, example/stats_distribution_exponential/example_exponential_pdf.f90, src/stdlib_random.fypp, src/stdlib_stats_distribution_exponential.fypp
Please refer to #679 for an explanation about the issue to solve and approach used. As discussed there, I've extended the approach to the exponential module.
IMO, this module still has other opportunities for improvement. For instance, I don't understand why `rvs_exp_array_` does not call the corresponding scalar procedure `rvs_exp_`, but instead _repeats_ the code in `rvs_exp_0_`. I will have a better look at it and, eventually, suggest another PR.
=> Extension of PR#679 to `stdlib_stats_distribution_exponential`

doc/specs/stdlib_stats_distribution_exponential.md, doc/specs/stdlib_stats_distribution_normal.md
This PR aims to fix some residual/undetected issues with PR #717 and #718 , namely:
* inline math was not rendering due to use of incorrect symbol.
* footnotes were not rendering due to missing colon.
* outdated example filename.
I was not able to detect these issues earlier because, in my local windows env, FORD in unable to parse certain Fortran source files (encoding issue) and aborts. I still have this issue (and assume other may as well), but I am going around it by excluding the problematic files.
=> fix doc stats-distribution-normal and stats-distribution-exponential

README.md
Fpm 0.8.2 introduced stdlib as a metapackage.
The previous way to include stdlib in a fpm project produces following error:
```
<ERROR> *cmd_run* Package error: Could not retrieve version string for metapackage key <stdlib>. Check syntax
```
=> Add warning for breaking change in fpm

src/stdlib_hash_32bit_water.fypp
This PR removes references to F202X (as it became F2023).
=> Remove reference to F202X

doc/specs/stdlib_bitsets.md, src/stdlib_bitsets.fypp, src/stdlib_bitsets_64.fypp, src/stdlib_bitsets_large.fypp, test/bitsets/test_stdlib_bitset_large.f90
PR opened following the issue reported in #723 and #726 (reported by @degawa )
Fixes #726
=> PR related to #726 and #723

.github/workflows/CI.yml, README.md
=> Addition of GCC 13 to CI

doc/specs/stdlib_string_type.md, src/stdlib_string_type.fypp, test/string/test_string_intrinsic.f90
Issue (see #731 and #735 for more detail): seg fault occurs when the input and output `string_type` variable is the same in `move`:
```fortran
call move( from, from)
```
@band-a-prend @nkevy @awvwgk  Would this proposition work for you? Could you test it with GCC 13, please?
Fixes #731 and #735
=> Proposal to fix the procedure `move` for string_type

doc/specs/stdlib_hashmaps.md
In the source code, the intent of the variable "conflict" in the procedure "map_entry" is "out", whereas in the documentation it is "in".
I corrected it from "in" to "out" on the documentation.
https://github.com/fortran-lang/stdlib/blob/82f35a57063f5db39ac8c469867d560327ff7cd0/src/stdlib_hashmaps.f90#L417-L431
=> Fixed incorrect intent of the variable "conflict" on hashmaps in document

.github/workflows/CI.yml, .github/workflows/ci_windows.yml, README.md, test/stats/test_rawmoment.f90
Fixes multiple issues with CI (Ubuntu + Intel and Windows)
Changes:
* Windows: GCC 13
* Ubuntu-latest: Intel LLVM (instead of Classic)
* Relax test in test_rawmoment due to change from Intel Classic to Intel LLVM
Note: CI for Windows works, but could be most likely improved (but how?)
=> Fix ci for windows and Intel ifx (#7)

test/hash_functions/SpookyV2Test.cpp
I could not compile tests on windows, since SpookyV2Test.cpp uses types from the cstdint header (e.g., uint64_t) without including the header. The type aliases are already defined in SpookyV2.h, so I have used those type aliases instead.
=> Fix undefined use of <cstdint> types

src/stdlib_bitsets.fypp, src/stdlib_bitsets_large.fypp, test/bitsets/test_stdlib_bitset_64.f90, test/bitsets/test_stdlib_bitset_large.f90
Fixes #746 
+ Addition of tests that trigger the bug with GFortran 11 and 12
Issue #746 reported by @degawa
=> Fix `bits()` in `bitset_type` before initialization

example/bitsets/example_bitsets_bit_count.f90, src/stdlib_bitsets_large.fypp
Related to issue #724 
Test case also added
=> Replaced btest() by popcnt() in bit_count_large()

README.md
Related to issue https://github.com/fortran-lang/stdlib/issues/734
=> Add CLI option for building with fpm

.gitignore
When running `fpm test` on the `stdlib-fpm` branch, some `.dat` and `.stream` files are being generated. After switching to the `master` branch, the files appear in the `git diff` because the extensions are currently missing in `.gitignore`. They are added herein.
=> Add `.dat` and `.stream` file extensions to `.gitignore` on `master` branch

.github/workflows/CI.yml, README.md
Address #776: 2021.4 -> 2023.1
=> Upgrade Intel-classic compiler in macOS CI

ci/fpm-deployment.sh
Cf.  https://github.com/fortran-lang/stdlib/pull/772#issuecomment-2039265289
@fortran-lang/stdlib
=> fpm branch: .f90 -> .F90 if preprocessed

src/stdlib_hashmap_chaining.f90, test/hashmaps/test_maps.fypp
The code provided in #785 (author: @jannisteunissen) revealed an issue with the procedure `remove` of the chaining maps.
This PR provides an additional test based on this code and a fix to the issue.
=> Fix in the procedure remove of chaining hashmaps

README.md
The current documentation on how to use stdlib in a project focuses on Cmake, see https://github.com/fortran-lang/stdlib?tab=readme-ov-file#using-stdlib-in-your-project
It can seem as is you actually need CMAKE to include stdlib (I got this impression). I think it would also be helpful to describe how to include stdlib in a regular makefile. This small change includes such documentation. I was not 100% sure about the paths: is it correct that the library is always in <build_folder>/src?
=> Add brief explanation on how to include stdlib in a Makefile

src/stdlib_str2num.fypp, test/string/test_string_to_number.fypp
Issue: GCC 13 (in the debug mode) returns some errors with the original code. This PR solves these errors.
cc: @jalvesz
=> Module str2num and related tests

ci/fpm-deployment.sh
cf. https://github.com/fortran-lang/stdlib/pull/787#issuecomment-2044239468
I understand the CI script is not supposed to be OS-agnostic, it should only live within the repo. 
However, it seems like people use the `stdlib-fpm` branch more than just as an fpm dependency, so, this fix is probably useful.
cc: @jalvesz @jvdp1
=> `fpm` deployment: workaround for case-insensitive fs

src/stdlib_linalg_blas.fypp, src/stdlib_linalg_blas_d.fypp, src/stdlib_linalg_blas_q.fypp, src/stdlib_linalg_blas_s.fypp
fix #793. This uses MathJax, so the equations are better formatted.
=> `rotm`, `rotmg` documentation

doc/specs/stdlib_linalg.md, example/linalg/example_blas_gemv.f90
1. Linking relying on `fpm.toml` requires adding the `link` keyword within the `[build]` section.
2. An error in the `example_blas_gemv` has been corrected.
=> Update linalg.md and example_blas_gemv.f90

.github/workflows/CI.yml
It looks like macOS-latest runners have arm architecture where gcc is not supported (at least yet).
For now, I suggest to select the macos version to 12.
=> macos-latest -> macos-12

test/linalg/test_linalg_lstsq.fypp
Problem: 
`1.0e-6` is too tight a tolerance for least squares on some systems (`1.0e-6 << sqrt(epsilon(0.0))`)
Example: failed CI job
https://github.com/fortran-lang/stdlib/actions/runs/9015259889/job/24769521465
Solution:
relax tolerance to `1.0e-4`
=> least squares: relax test tolerance

src/stdlib_linalg_lapack_c.fypp, src/stdlib_linalg_lapack_d.fypp, src/stdlib_linalg_lapack_q.fypp, src/stdlib_linalg_lapack_s.fypp, src/stdlib_linalg_lapack_w.fypp, src/stdlib_linalg_lapack_z.fypp
Fix #810 @jvdp1 @sscalpone
Renaming this variable rather than the logical kind would minimize the number of changes to the code.
=> `lk` -> `llk` in `*sytrd_sy2sb`

src/stdlib_linalg_determinant.fypp, test/linalg/test_linalg_determinant.fypp
I noticed a typo in `det` that does not deallocate the internal pointer matrix properly: it should be when the temporary is created (`copy_a==.true.`):
https://github.com/fortran-lang/stdlib/blob/206f84a0915d1e7ac31e7d2ad254c2b88ada2695/src/stdlib_linalg_determinant.fypp#L227
I don't know why an error was never printed in the tests, as it should be impossible to deallocate the target
of a pointer, if this is not `allocatable`. 
Anyways this is a fix for it, plus an additional test. 
=> Fix: `copy_a` deallocation in `determinant`

doc/specs/stdlib_linalg.md, src/stdlib_linalg_least_squares.fypp, test/linalg/test_linalg_lstsq.fypp
Fix #817. 
for `Ax=b` with `shape(A) == [m, n]`:
- Subroutine interface: allow `size(x,1)>=n`. 
- if also `size(x,1)>=m`: use as temporary storage and do not reallocate
- otherwise: allocate temporary for `*GESV` interface
- Function interface: always return `size(x,1)==n`
cc: @jvdp1 @jalvesz @loiseaujc
=> `lstsq`: return correct array size

src/stdlib_linalg_lapack.fypp, src/stdlib_linalg_lapack_aux.fypp, src/stdlib_linalg_lapack_c.fypp, src/stdlib_linalg_lapack_d.fypp, src/stdlib_linalg_lapack_q.fypp, src/stdlib_linalg_lapack_s.fypp, src/stdlib_linalg_lapack_w.fypp, src/stdlib_linalg_lapack_z.fypp
Fix #825. 
- Remove `pure` attribute from all routines that may use the `openmp` runtime upward. 
- [Reference to the OpenMP standard](https://www.openmp.org/spec-html/5.1/openmpch3.html): 
> OpenMP runtime library routines may not be called from PURE or ELEMENTAL procedures.
cc: @jvdp1 @fortran-lang/stdlib
=> linalg: remove `pure` attr from procedures using `openmp` runtime

doc/specs/stdlib_sorting.md, src/stdlib_sorting.fypp, src/stdlib_sorting_ord_sort.fypp, src/stdlib_sorting_radix_sort.f90, src/stdlib_sorting_sort.fypp, src/stdlib_sorting_sort_index.fypp, test/sorting/test_sorting.f90
Related to [this Discouse discussion](https://fortran-lang.discourse.group/t/error-there-is-no-specific-subroutine-for-the-generic-sort-index/1728/14) and to #822
=> Rename `int size` to `int_index`

API-doc-FORD-file.md
Fixes #838 
Replacing the link to a valid does not solve the issue.
The same issue is also in [`fpm API website`](https://fortran-lang.github.io/fpm/).
=> Update author picture in API documentation webpage

src/stdlib_math_meshgrid.fypp
`removesuffix` used in `stdlib_math_meshgrid` requires Python >3.9. 
Here is a small change to avoid the requirement of Python >3.9.
@igirault : was there a special need to use `removesuffix`? Do I overlook something? Or are my changes satisfying?
\cc @perazz @jalvesz
=> Rewrite fypp directive to avoid the use of removesuffix in stdlib_math_meshgrip

src/stdlib_sorting.fypp, src/stdlib_sorting_ord_sort.fypp, src/stdlib_sorting_sort_index.fypp
This PR aims to simplifiy the implementation of `sort_index`, without modifying the API. So, `sort_index` still accept an array `index` of kind `int_index` or `int_index_low`, but all iterations and counts are internally done using `int_index` integers.
This is a first step to extend `sort_index` to a procedure that accepts an array `index` of a intrinsic type `integer`, `real`, `complex`, ....
Note: these changes partly revert some changes done in #829 and can be compared against #824 (see [here](https://github.com/fortran-lang/stdlib/compare/3d283a7a70c8461496b870c4448f8d74f7b4563d...jvdp1:stdlib:split_sort_index) for a comparison with the original implementation)
Note2: these changes are in agreement with the implementation in `ord_sort`.
cc: @perazz @jalvesz
=> `sort_index`: use of only `int_index` iterators inside `sort_index`

.github/workflows/ci_windows.yml
Address https://github.com/fortran-lang/stdlib/issues/853.
=> Remove `msys` from CI and install `fypp` via msys2 package

.github/workflows/ci_windows.yml, .github/workflows/doc-deployment.yml
Versions @v1 and @v2 are deprecated, this causes CI builds to fail
- See: https://github.com/fortran-lang/stdlib/actions/runs/10847866794/job/30103827108
- Deprecation notice: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/
@jvdp1 @fortran-lang/stdlib
=> CI: upgrade to upload-artifact@v4

doc/specs/stdlib_linalg.md
Due to lack of complaints, 
this is a proposal to stabilize the LAPACK-based high-level Linear Algebra APIs that have appeared in stdlib release 0.7.0 
(all but `Cholesky`, `norm`s and `qr` factorization). 
cc: @jvdp1 @jalvesz @fortran-lang/stdlib
=> API: make LAPACK-backed APIs since Release <=0.7.0 `stable`

src/stdlib_linalg_inverse.fypp
During the fix of `unused-dummy-argument` in https://github.com/fortran-lang/stdlib/pull/879, I see this case where the pivot argument is not used, but it seems it should be definitely be passed to the linalg_invert_inplace function.
I made a different PR since it is no longer a refactoring but a real fix.
=> Fix missing argument to linalg_invert_inplace_ call in linalg_invert_split

src/stdlib_linalg_svd.fypp
The procedure `gesdd` might return values for storage space larger than `huge(lwork)`, resulting in a negative value fro `lwork`. Here is a proposition to solve this issue.
=> svd - check the size of storage space

config/fypp_deployment.py
Small fix for the build option in the fypp_deployment script and change default maxrank. The previous command line construc worked in Linux but was not working on windows.
=> fix fypp_deployment build and set maxrank default to 4 as in cmake

example/hashmaps/example_hashmaps_get_other_data.f90, example/hashmaps/example_hashmaps_remove.f90, example/hashmaps/example_hashmaps_set_other_data.f90, example/linalg/example_determinant.f90, example/linalg/example_eigvals.f90, example/linalg/example_eigvalsh.f90, example/linalg/example_state2.f90, example/selection/selection_vs_sort.f90, src/stdlib_linalg_blas_c.fypp, src/stdlib_linalg_blas_d.fypp, src/stdlib_linalg_blas_q.fypp, src/stdlib_linalg_blas_s.fypp, src/stdlib_linalg_blas_w.fypp, src/stdlib_linalg_blas_z.fypp, src/stdlib_linalg_cholesky.fypp, src/stdlib_linalg_eigenvalues.fypp, src/stdlib_linalg_lapack_c.fypp, src/stdlib_linalg_lapack_d.fypp, src/stdlib_linalg_lapack_s.fypp, src/stdlib_linalg_lapack_w.fypp, src/stdlib_linalg_lapack_z.fypp, src/stdlib_linalg_least_squares.fypp, src/stdlib_linalg_svd.fypp, src/stdlib_specialfunctions_gamma.fypp
Cleaning duty, warnings are generates with
`fpm build --verbose  --flag '-Wunused-variable -Wunused-dummy-argument -Wunused-parameter'
`
> ### Progress
> * [x]  42 unused-variable
> * [x]  15 unused-parameter
> * [x]  12/67 unused-dummy-argument
> * [ ]  55/67 unused-dummy-argument
Leaving 55 unused-dummy-argument warnings unresolvable, see conversation about those.
=> Fix warnings [-Wunused-xxx] from compilation

doc/specs/stdlib_stats_distribution_normal.md
There was a missing $\pi$ in the normalization term in the documentation of the pdf_normal function.
=> Fix Gaussian distribution formula in documentation

src/stdlib_io.fypp
`loadtxt` keeps failing often in the CI tests, [see e.g. here](https://github.com/fortran-lang/stdlib/actions/runs/11934455143/job/33263598092?pr=892) or #862 . 
Ifort output is: 
```
160/340 Test #161: loadtxt ................................***Failed    0.01 sec
forrtl: severe (66): output statement overflows record, unit -5, file Internal Formatted Write
Image              PC                Routine            Line        Source             
example_loadtxt    0000000000444ECE  Unknown               Unknown  Unknown
example_loadtxt    0000000000404AF2  Unknown               Unknown  Unknown
example_loadtxt    0000000000404253  Unknown               Unknown  Unknown
example_loadtxt    00000000004041BD  Unknown               Unknown  Unknown
libc.so.6          00007F7E6A629D90  Unknown …
```
=> loadtxt: increase length of internal buffers

src/stdlib_io.fypp
Address #890. 
Some compilers, if run with `-std=f2008`, do not accept `error stop + character` .
@jvdp1 @MilanSkocic
=> Revert "`call error_stop` -> `error stop`"

doc/specs/stdlib_ascii.md, src/stdlib_ascii.fypp
Promote ascii functions from pure to elemental for potentially better optimization and ease use for array expressions manipulation.
=> promote ascii functions to elemental

.github/workflows/CI.yml
`macos-12` is deprecated by the GitHub runners, an update to macos-13 is proposed. 
cc: @jvdp1 @fortran-lang/stdlib
=> CI: deprecate macos-12

.github/workflows/ci_windows.yml, README.md
This PR removes MINGW32 from the Windows CI checks.  This version of MINGW receives limited support, and I don't believe it makes sense to use for validation of future development.  This change was originally suggested in this [PR](https://github.com/fortran-lang/stdlib/pull/854).
=> Remove mingw32

example/linalg/example_sparse_from_ijv.f90
=> Fix output format in sparse example

src/stdlib_io.fypp
Using `getline` instead of non-advancing io, we may be able to fix #924 
=> Proposal to upgrade `number_of_columns`

src/stdlib_linalg_eigenvalues.fypp, test/linalg/test_linalg_eigenvalues.fypp
Fix #927. 
`rwork` size is different in `*GGEV` (`8*n`) vs. in `*GEEV` (`2*n`), I had overlooked that. 
cc: @jalvesz @jvdp1 
Thank you
=> Fix generalized `eig` rwork size

src/lapack/stdlib_linalg_lapack_aux.fypp
Instead of old-style, possibly inf/nan trapping checks, use the Modern Fortran `ieee_arithmetic` module. 
Fix #932 
cc: @loiseaujc @jalvesz @jvdp1
=> `ieeeck`: use `ieee_arithmetic` intrinsics 

src/stdlib_specialfunctions_gamma.fypp
This PR tries to address #898 
The problem was in the interface `gpx` (meant for internal use only) which had two procedures for `x, p are real` and `x is real, p is an integer`, `p being > 0` in all cases
Everything was fine with the second procedure but in the first one it is required that ([Fast and accurate evaluation of a
generalized incomplete gamma function](hal.science/hal-01329669v2/document)) `when x < 0, p be an integer` which wasn't actually programmed in the procedure itself but was being taken care of as and when requiring to call `gpx` in such a case. like so https://github.com/fortran-lang/stdlib/blob/master/src/stdlib_specialfunctions_gamma.fypp#L1078-L1099
And hence this was not found earlier as the chunk of code was in the case when `x<0 and p<p_lim(x)` (check Algorithm …
=> fix: gamma functions

doc/specs/stdlib_system.md, example/system/CMakeLists.txt, example/system/example_get_runtime_os.f90, example/system/example_os_type.f90, src/stdlib_system.F90, test/system/CMakeLists.txt, test/system/test_os.f90
This PR is spun off #904 for clarity.  
Add OS detection routines:  
- `get_runtime_os` – Determines the OS at runtime using environment checks.  
- `OS_TYPE` – Cached version of `get_runtime_os` for efficiency.  
- `OS_NAME` – Return the OS name as a string.    
Test programs require that stdlib is never run on an unknown OS. 
=> system: OS type query

doc/specs/stdlib_system.md, example/system/CMakeLists.txt, example/system/example_null_device.f90, src/stdlib_system.F90, src/stdlib_system_subprocess.F90, src/stdlib_system_subprocess.c, test/system/test_os.f90
Standardize the `null_device` function (previously in the subprocess submodule). 
This PR aims to provide a standard cross-platform reference to the null device file name. 
- uses a macro-based C static interface for zero overhead
- Add test and examples
=> system: `null_device`

src/stdlib_io.fypp
Using the previous format directive would have caused a runtime error if there was an error skipping the required rows as there were only 3 format arguments given (instead of 4)
This PR fixes that and provides a useful error message with the required arguments
=> small fix for `loadtxt`

src/stdlib_constants.fypp
Reduced Planck constant is `h/2pi`, a factor of 2 was missing.
=> fix: hbar value

src/stdlib_math_is_close.fypp, src/stdlib_stats_corr.fypp, src/stdlib_stats_cov.fypp
fix #953. 
cc: @jvdp1 @jalvesz @Beliavsky
=> remove unnecessary `merge(.true.,.false.,)`

doc/specs/stdlib_system.md, example/system/CMakeLists.txt, example/system/example_is_directory.f90, src/stdlib_system.F90, src/stdlib_system_subprocess.F90, src/stdlib_system_subprocess.c, test/system/CMakeLists.txt, test/system/test_filesystem.f90
This PR is spun off #904 for clarity. 
- It provides a `logical` function to evaluate whether a given path is a directory. 
- On Windows, it natively works both with `/` and `\` separators. 
- Relies on C functions, to avoid Fortran pre-processor macros and path swapping, that would be slow. 
Some questions to discuss that come to my mind: 
- Should this be part of `stdlib_system`, `stdlib_io`, or maybe a `submodule(stdlib_system) stdlib_system_filesystem`? or else?
- Should we begin standardizing the C-side names somehow? They use the same global namespace, so we should start being careful imho. 
=> system: `is_directory`

example/specialfunctions_gamma/example_gamma.f90, example/specialfunctions_gamma/example_log_gamma.f90, src/stdlib_specialfunctions_gamma.fypp, test/specialfunctions/test_specialfunctions_gamma.fypp
Fix #964. 
gamma functions always require quad-precision even when not `WITH_QP`.
Propose to: instead of hard-coded, the `KIND`s are taken from the lists of available ones. 
Because they're sorted with increasing accuracy, generate all accuracies except the last one 
- for single precision: the `i+1`-th accuracy is used.
- for all others: the maximum available accuracy is used (because when `xdp` is available, it is not enough to guarantee accuracy for `dp` evaluation: `qp` is always needed if present).
This is a more generalized version than #967.
cc: @jvdp1 @jalvesz @loiseaujc @osada-yum
=> specialfunctions: generalize `gamma` precision

doc/specs/stdlib_linalg.md, src/stdlib_linalg.fypp, src/stdlib_linalg_diag.fypp
This is a minor update that sets the `diag` function as pure.
=> stdlib_linalg: declare the `diag` function as pure

test/linalg/test_linalg_pseudoinverse.fypp
this PR attempts to fix some CI failures by relaxing the `pinv` (pseudoinverse) test tolerance.
`pinv` works with singular matrices and the accuracy of the inverse in the test may be affected by the random number choice.
=> `linalg`: slightly increase test tolerance

WORKFLOW.md
I noticed that the diagram included to explain the collab script didn't show properly in the documentation html. Adding the text quotes enables a proper visualization of the diagram for both the original markdown and the html.
Current layout in the docs:
After fix:
=> fix: collab diagram layout fix

CMakeLists.txt, test/linalg/test_linalg_cholesky.fypp, test/linalg/test_linalg_determinant.fypp, test/linalg/test_linalg_eigenvalues.fypp, test/linalg/test_linalg_inverse.fypp, test/linalg/test_linalg_lstsq.fypp, test/linalg/test_linalg_mnorm.fypp, test/linalg/test_linalg_norm.fypp, test/linalg/test_linalg_pseudoinverse.fypp, test/linalg/test_linalg_qr.fypp, test/linalg/test_linalg_schur.fypp, test/linalg/test_linalg_solve.fypp, test/linalg/test_linalg_svd.fypp, test/stringlist/test_append_prepend.f90, test/stringlist/test_insert_at.f90
Introduces workarounds for known gcc-15 issues: 
- tests: replace array constructors `tests = [tests, new_unittest(...)]` with a tiny helper function `add_test`
- strings: do not use array constructors `[string_t(), string_t(),...]`
- build: add `-Wno-external-argument-mismatch` (to be replaced by PR #1007 when merged). 
cc: @jvdp1 @zoziha @jalvesz
=> GCC 15.1 fixes

src/stdlib_strings.fypp, test/string/test_string_strip_chomp.f90
To prevent any indices from becoming non-positive
Cause of CI failures in #999
=> fix: index handling in `chomp`

src/stdlib_intrinsics_dot_product.fypp, test/intrinsics/test_intrinsics.fypp
addresses #1016 
cc: @loiseaujc
=> fix: complex dot_product formulation
